[package]
name = "rust-action"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
minijinja = "2.12.0"
serde = { version = "1.0.228", features = ["derive"] }
serde-saphyr = "0.0.6"
serde_json = "1.0.145"

